-- liquibase formatted sql

-- changeset gnev:1
CREATE TABLE IF NOT EXISTS chat (i_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key ,
                                    i_tg_chat_id integer unique);

comment on table chat is 'Community chat';
comment on column chat.i_id is 'Внутренний идентификатор чата';
comment on column chat.i_tg_chat_id is 'Глобальный идентификатор чата';