-- liquibase formatted sql

-- changeset gnev:1
CREATE TABLE IF NOT EXISTS chatusers
(
    i_id       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key,
    s_nickname varchar(128) NULL,
    id_chat    INT references chatusers (i_id),
    i_floor    INT,
    i_section  INT,
    i_flat     INT
);

comment on table chatusers is 'Жители';
comment on column chatusers.i_id is 'Внутренний идентификатор жителя';
comment on column chatusers.s_nickname is 'Телеграм-ник пользователя';
comment on column chatusers.id_chat is 'Глобальный идентификатор чата';
comment on column chatusers.i_floor is 'Этаж';
comment on column chatusers.i_section is 'Номер плана на этаже';
comment on column chatusers.i_flat is 'Номер квартиры';