-- liquibase formatted sql

-- changeset liquibase:1
CREATE TABLE IF NOT EXISTS address (i_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key ,
                                    s_city BIGINT NULL,
                                    s_street VARCHAR(256),
                                    s_house_number VARCHAR(16));

comment on table address is 'Справочник домов';
comment on column address.i_id is 'Идентификатор дома';
comment on column address.s_city is 'Город';
comment on column address.s_street is 'Улица';
comment on column address.s_house_number is 'Номер дома';

-- changeset liquibase:2
CREATE TABLE IF NOT EXISTS people (i_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key ,
                                   s_nickname BIGINT NULL,
                                   id_address INT references address(i_id),
                                   i_floor INT,
                                   i_floor_part INT,
                                   i_flat INT);

comment on table people is 'Жители дома';
comment on column people.i_id is 'Идентификатор жителя';
comment on column people.id_address is 'Идентификатор дома';
comment on column people.i_floor is 'Этаж';
comment on column people.i_floor_part is 'Номер плана на этаже';
comment on column people.i_flat is 'Номер квартиры';
